---
 - name: clone git project
   git:
    repo: https://github.com/opstree/spring3hibernate.git
    version: master
    dest: /home/ubuntu/test
    force: yes
     
 - name: copy databse propert file
   template:
    src: database.properties.j2
    dest: "/home/ubuntu/test/src/main/resources/database.properties"

    # - name: build Dockerfile
    #command: "docker build -t test -f /home/ubuntu/test/Dockerfile /home/ubuntu/test/."

 - name: Run Docker container
   command: "docker run -d --name test -p 7777:8080 test"

