---
 - name: clone git project
   git:
    repo: https://github.com/opstree/spring3hibernate.git
    version: master
    dest: /home/ubuntu/opstree
    force: yes
    
 - name: build Dockerfile
   command: "docker build -t opstree -f /home/ubuntu/opstree/Dockerfile /home/ubuntu/opstree/."

 - name: Run Docker container
   command: "docker run -d --name test --restart always -p 80:8080 opstree"

