---
 - name: install openjdk-8-jdk
   apt:
    update_cache: yes
    name: openjdk-8-jdk
    state: latest
    install_recommends: no

 - shell: echo JAVA_HOME is $JAVA_HOME
   environment:
     JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
   register: shellout
 - debug: var=shellout

